language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer install --prefer-source

script:
    - php vendor/bin/phpunit

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true